// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5pZnHrZvqHTgjOq4B_5DiJ4QemdDXDLY',
    appId: '1:575154789152:web:8c31c360d2cff3cf0c9545',
    messagingSenderId: '575154789152',
    projectId: 'food-ff71f',
    authDomain: 'food-ff71f.firebaseapp.com',
    storageBucket: 'food-ff71f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhVE85gI69PGD41BHAZGnR4YJQ0med8YQ',
    appId: '1:575154789152:android:b35dbb6964f9cb960c9545',
    messagingSenderId: '575154789152',
    projectId: 'food-ff71f',
    storageBucket: 'food-ff71f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGpzcYaY5Ln9LUKzhZgycKnVIf_MmM1bA',
    appId: '1:575154789152:ios:774e0b881dd063790c9545',
    messagingSenderId: '575154789152',
    projectId: 'food-ff71f',
    storageBucket: 'food-ff71f.appspot.com',
    iosBundleId: 'com.example.food',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGpzcYaY5Ln9LUKzhZgycKnVIf_MmM1bA',
    appId: '1:575154789152:ios:00b320847355c0c50c9545',
    messagingSenderId: '575154789152',
    projectId: 'food-ff71f',
    storageBucket: 'food-ff71f.appspot.com',
    iosBundleId: 'com.example.food.RunnerTests',
  );
}
